spring:
  application:
    name: first
  data:
    mongodb:
      uri: mongodb://localhost:27017/Pagination-topic

server:
  port:9090

logging:
  level:
    root: INFO
    com.pagination.first: DEBUG
    org.springframework.web: DEBUG